export const safetyMenuItems = [
  {
    id: 1,
    title: "Inicio",
    department_id: 2,
    order: 1,
    url: "/safety",
    icon: "menuItemDefault",
    description: "",
  },
  {
    id: 2,
    title: "Dashboard",
    department_id: 2,
    order: 2,
    url: "/safety/dashboard",
    icon: "menuItemDefault",
    description: "",
  },
  {
    id: 3,
    title: "NR1",
    department_id: 2,
    order: 3,
    url: "/safety/nr1",
    icon: "menuItemDefault",
    description: "",
    items: [
      {
        id: 1,
        menu_id: 3,
        title: "GRO",
        order: 1,
        url: "/safety/nr1/gro",
        icon: "menuItemDefault",
      },
      {
        id: 2,
        menu_id: 3,
        title: "PGR",
        order: 2,
        url: "/safety/nr1/pgr",
        icon: "menuItemDefault",
      },
    ],
  },
  // {
  //   id: 4,
  //   title: "NR6",
  //   department_id: 2,
  //   order: 4,
  //   url: "/safety/nr6",
  //   icon: "menuItemDefault",
  //   description: "",
  // },
];
