export const managementMenuItems = [
  {
    id: 1,
    title: "Inicio",
    department_id: 4,
    order: 1,
    url: "/management",
    icon: "menuItemDefault",
    description: "",
  },
  {
    id: 4,
    title: "Localização",
    department_id: 4,
    order: 4,
    url: "/management/localizations",
    icon: "menuItemDefault",
    description: "",
    subMenu: [
      {
        id: 1,
        menu_id: 4,
        title: "Prédio",
        order: 3,
        url: "/management/localizations/buildings",
        icon: "menuItemDefault",
      },
      {
        id: 3,
        menu_id: 4,
        title: "Divisão",
        order: 2,
        url: "/management/localizations/building-divisions",
        icon: "menuItemDefault",
      },
      {
        id: 2,
        menu_id: 4,
        title: "Andar",
        order: 1,
        url: "/management/localizations/building-floors",
        icon: "menuItemDefault",
      },
      {
        id: 4,
        menu_id: 4,
        title: "Tipo de espaço",
        order: 4,
        url: "/management/localizations/building-spaces",
        icon: "menuItemDefault",
      },
    ],
  },
  {
    id: 2,
    title: "Centro de custo",
    department_id: 4,
    order: 2,
    url: "/management/cost-center",
    icon: "menuItemDefault",
    description: "",
  },
  {
    id: 3,
    title: "Grupo de pagamento",
    department_id: 4,
    order: 3,
    url: "/management/payment-groups",
    icon: "menuItemDefault",
    description: "",
  },
  {
    id: 5,
    title: "Projetos",
    department_id: 4,
    order: 5,
    url: "/management/projects",
    icon: "menuItemDefault",
    description: "",
  },
];
