export const managerMenuItems = [
  {
    id: 1,
    name: "Inicio",
    department_id: 4,
    order: 1,
    url: "/manager",
    icon: "menuItemDefault",
    description: "",
  },
  {
    id: 4,
    name: "Localização",
    department_id: 4,
    order: 4,
    url: "/manager/localizations",
    icon: "menuItemDefault",
    description: "",
    subMenu: [
      {
        id: 1,
        menu_id: 4,
        name: "Prédio",
        order: 3,
        url: "/manager/localizations/buildings",
        icon: "menuItemDefault",
      },
      {
        id: 3,
        menu_id: 4,
        name: "Divisão",
        order: 2,
        url: "/manager/localizations/building-divisions",
        icon: "menuItemDefault",
      },
      {
        id: 2,
        menu_id: 4,
        name: "Andar",
        order: 1,
        url: "/manager/localizations/building-floors",
        icon: "menuItemDefault",
      },
      {
        id: 4,
        menu_id: 4,
        name: "Tipo de espaço",
        order: 4,
        url: "/manager/localizations/building-spaces",
        icon: "menuItemDefault",
      },
    ],
  },
  {
    id: 2,
    name: "Centro de custo",
    department_id: 4,
    order: 2,
    url: "/manager/cost-center",
    icon: "menuItemDefault",
    description: "",
  },
  {
    id: 3,
    name: "Grupo de pagamento",
    department_id: 4,
    order: 3,
    url: "/manager/payment-groups",
    icon: "menuItemDefault",
    description: "",
  },
  {
    id: 5,
    name: "Projetos",
    department_id: 4,
    order: 5,
    url: "/manager/projects",
    icon: "menuItemDefault",
    description: "",
  },
];
