export const safetyMenuItems = [
  {
    id: 1,
    name: "Inicio",
    department_id: 2,
    order: 1,
    url: "/safety",
    icon: "menuItemDefault",
    description: "",
  },
  {
    id: 2,
    name: "Dashboard",
    department_id: 2,
    order: 2,
    url: "/safety/dashboard",
    icon: "menuItemDefault",
    description: "",
  },
  // {
  //   id: 3,
  //   name: "NR1",
  //   department_id: 2,
  //   order: 3,
  //   url: "/safety/nr1",
  //   icon: "menuItemDefault",
  //   description: "",
  //   subMenu: [
  //     {
  //       id: 1,
  //       menu_id: 3,
  //       name: "GRO",
  //       order: 1,
  //       url: "/safety/nr1/gro",
  //       icon: "menuItemDefault",
  //     },
  //     {
  //       id: 2,
  //       menu_id: 3,
  //       name: "PGR",
  //       order: 2,
  //       url: "/safety/nr1/pgr",
  //       icon: "menuItemDefault",
  //     },
  //   ],
  // },
  // {
  //   id: 4,
  //   name: "NR6",
  //   department_id: 2,
  //   order: 4,
  //   url: "/safety/nr6",
  //   icon: "menuItemDefault",
  //   description: "",
  // },
];
